markdown: kramdown

plugins:
  - jekyll-seo-tag

includes_dir: _includes

permalink: /blog/:month-:day-:year/:title/

exclude:
  - /**/.git/*
  - _posts

collections:
  projects:
    output: false
  software:
    output: true
    permalink: /software/:path/
  specs:
    output: true
    permalink: /specs/:path/
  posts:
    output: true
    permalink: /blog/:month-:day-:year/:title/
  pages:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
  - scope:
      path: _software
      type: software
    values:
      layout: product
  - scope:
      path: _specs
      type: specs
    values:
      layout: spec
