markdown: kramdown

includes_dir: .

permalink: /blog/:year-:month-:day-:title/

# algolia_search:
#   api_key: ''
#   index_name: ''
# Uncomment this if you want to use Algolia’s search.
# It’s free for open-source projects.

exclude:
  - home-hero.html
  - title.html
  - nav-links.html
  - flavor-sample-summary.html
  - project-nav.html
  - /**/.git/*
  - /_projects/**/_*_repo/*
  - /_projects/*/assets/css/*
  - /_projects/**/docs/*
  - .sass-cache/

external_links:
  selector: 'body.site--project main a, body.site--hub.layout--post main a'
  ignored_selectors:
    - .layout--home a
    - a[href*=travis]
    - a[href*=coverity]
    - a[href*=codecov]

landing_priority: [software, specs, blog]

plugins:
  - jekyll-theme-rop
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-data
  - jekyll-asciidoc
  - jekyll-redirect-from
  - kramdown-parser-gfm
  - kramdown-syntax-coderay

collections:
  projects:
    output: false
  software:
    output: true
    permalink: /software/:path/
  specs:
    output: true
    permalink: /specs/:path/
  posts:
    output: true
    permalink: /blog/:month-:day-:year/:title/
  pages:
    output: true
    permalink: /:name/

fontawesome_cdn:
  version: v5.8.1
  integrity: "sha384-g5uSoOSBd7KkhAMlnQILrecXvzst9TdC09/VM+pjDTCM+1il8RHz5fKANTFFb+gQ"
# Only applies if no_auto_fontawesome is not set.

no_auto_fontawesome: false
# If set to yes, site (with default design) must specify <script> elements
# that make required FA styles available in SVG mode.

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
  - scope:
      path: _software
      type: software
    values:
      layout: product
  - scope:
      path: _specs
      type: specs
    values:
      layout: spec
